### ISSUE TITLE
getPubYear() not always return a date

### ISSUE THREAD

**Issue by sujliu** [tmpjr/pubmed#4]
Hi,

I was trying to get the publication date for this PubMed ID: 2342890:

`$api = new PubMed\PubMedId();
$article = $api->query(2342890);
print_r($article->getPubYear());`

but it returned an empty value probably related to the following tagging (see https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&rettype=xml&retmode=text&id=2342890)

`<JournalIssue CitedMedium="Print">
<PubDate>
<MedlineDate>1990 May-Jun</MedlineDate>
</PubDate>
</JournalIssue>`

Are you going to address this type of issue at some point?

Also, I can't seem to get DOI by this: $article->getDoid(). Did I miss anything? 

Thanks for your wonderful library!

**Comment by tmpjr** [comment]
Hi, thanks so much for your complement and pointing out this issue. I will take a look at it but feel free to try and fix it and make a pull request and I'll be happy to merge it. I just don't have much time these days but I'll take a look.

**Comment by sujliu** [comment]
Thanks much for getting back to me. I've made some changes, sent a pull request, and would appreciate if you could take a look.
